apiVersion: starrocks.com/v1alpha1
kind: StarRocksCluster
metadata:
  name: starrockscluster-sample
  namespace: starrocks
spec:
  starRocksFeSpec:
    image: starrocks/alpine-fe:2.4.1
    replicas: 3
    requests:
      cpu: 4
      memory: 16Gi
  starRocksBeSpec:
    image: starrocks/centos-be:2.4.1
    replicas: 3
    requests:
      cpu: 4
      memory: 8Gi